# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOffonpw():
  def setup_method(self, method):
    self.driver = webdriver.Firefox(firefox_profile="/home/igors/.mozilla/firefox/")
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_offonpw(self):
    self.driver.get("http://172.16.14.65/")
    self.driver.set_window_size(1018, 817)
    self.driver.find_element(By.LINK_TEXT, "Outlet").click()
    self.driver.find_element(By.ID, "C11").click()
    self.driver.find_element(By.ID, "T21").click()
    assert self.driver.switch_to.alert.text == "reboot the outlet"
    self.driver.switch_to.alert.accept()
  
